### ISSUE TITLE
Question regarding name

### ISSUE THREAD

**Issue by drujensen** [waterlink/mysql_adapter.cr#1]
Curious why you went with the name mysql_adapter.cr instead of crystal_mysql_adapter.

**Comment by waterlink** [comment]
If you look at most of the libraries out there, they have this pattern: `some_name.cr`. Like `webmock.cr` or `timecop.cr`. Look here: http://crystalshards.herokuapp.com/ - not majority of them have `.cr` at the end, but certain amount.

**Comment by drujensen** [comment]
Yeah.  I was just wondering if that was just a trend or if there was a reason behind it.   Seems like there are two competing naming conventions.  crystal_\* or *.cr.  I don't really have a preference except wishing to find some consistency when looking for projects.

**Comment by alex-fedorov** [comment]
Actually `*.cr` is a convention I have started with my first `timestamp.cr` and `timecop.cr`, then somebody started doing the same, somebody not.

I think `something.cr` is a bit better than `crystal-something` because of shorter length. Especially if "something" is itself already not so short (like in case of `mysql_adapter.cr` and `active_record.cr`).

Why I add `.cr` at all? Because I work with multiple languages simultaneously and don't want to confuse myself with plain `active_record`.

**Comment by drujensen** [comment]
I see.  Ok.  I was originally confused seeing a *.cr file in the Projectfile because it looks like a file being included instead of a repository, but I totally agree we need something to differentiate crystal from other repos in the name.
